agent:
  id: workflow-01
  name: workflow-01
  description: "This is a mathematical calculation assistant"
  env:
    base_url:
      description: "the base url of the llm"
      type: str
      default: "http://127.0.0.1:8000/v1"
  input:
    query1:
      description: "源提示词"
      required: True
      type: str
      default: ""
    query2:
      description: "生成的提示词个数"
      type: str
      default: ""
  output:
    content:
      description: "content of result"
      type: list[str]
      source: reference
      reference: llm.list
nodes:
  - name: if_route
    type: condition
    prev: __start__
    if:
      logic_operator: and
      condition:
        - operator: em
          operand: user_input.query1
          op_type: int
          source: input
          value: 20
      next: if_rand
    elif:
      - logic_operator: or
        condition:
          - operator: em
            operand: user_input.query2
            op_type: int
            source: input
            value: 20
        next:
          - "elif_rand"
    else: llm
